export const interests = [
    {id: 1, label: 'Общение'},
    {id: 2, label: 'Флирт'},
    {id: 3, label: 'Семья'},
    {id: 4, label: 'Вирт'},
    {id: 5, label: 'Женат'},
    {id: 6, label: 'Замужем'},
    {id: 7, label: 'Холост'},
    {id: 8, label: 'Незамужем'},
    {id: 9, label: 'ЗОЖ'},
    {id: 10, label: 'Спорт'},
    {id: 11, label: 'Искусство'},
    {id: 12, label: 'Путешествия'},
    {id: 13, label: 'Музыка'},
    {id: 14, label: 'Авто'},
    {id: 15, label: 'Мото'},
    {id: 16, label: 'Активный отдых'},
    {id: 17, label: 'Курю'},
    {id: 18, label: 'Люблю выпить'},
    {id: 19, label: 'Не курю'},
    {id: 20, label: 'Не пью'},
];
